theme: jekyll-theme-cayman
title: "Embedding LLM Chatbots into Qualtrics Surveys"
description: "Research by Zhongren Chen, Joshua Kalla, Quan Le, Shinpei Nakamura-Sakai, Jasjeet Sekhon, Ruixiao Wang"

# GitHub integration
github:
  repository_url: https://github.com/joshuakalla/llm_persuasion
  repository_name: llm_persuasion
  owner_name: joshuakalla

# Build settings
markdown: kramdown
highlighter: rouge

# Author information
authors:
  - "Zhongren Chen"
  - "Joshua Kalla" 
  - "Quan Le"
  - "Shinpei Nakamura-Sakai"
  - "Jasjeet Sekhon"
  - "Ruixiao Wang"
