title: "Embedding LLM Chatbots into Qualtrics Surveys"
authors: 
  - Zhongren Chen
  - Joshua Kalla
  - Quan Le
  - Shinpei Nakamura-Sakai
  - Jasjeet Sekhon
  - Ruixiao Wang
layout: default
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
  
# GitHub integration
github:
  repository_url: "https://github.com/joshuakalla/llm_persuasion"
  is_project_page: true
  show_downloads: true
  
# Page layout
classes: wide
toc: true
toc_label: "Guide Contents"
toc_sticky: true
